version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: desafio_backend_mongodb
    restart: unless-stopped
    ports:
      - "27028:27017"
    environment:
      - MONGO_INITDB_DATABASE=desafio_senior
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
